apiVersion: v1
kind: Namespace
metadata:
  name: identity-monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: identity-monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: identity-monitoring:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://identity_user:identity_password@postgres-service:5432/identity_monitoring"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: DEPLOYMENT_MODE
          value: "hybrid"
        - name: CLOUD_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: cloud-endpoint
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: identity-api-service
  namespace: identity-monitoring
spec:
  selector:
    app: identity-api
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: identity-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "identity_monitoring"
        - name: POSTGRES_USER
          value: "identity_user"
        - name: POSTGRES_PASSWORD
          value: "identity_password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: identity-monitoring
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: identity-monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: identity-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: identity-monitoring
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
  namespace: identity-monitoring
data:
  cloud-endpoint: "https://cloud.identity-monitoring.com"
  monitoring-interval: "60"
  alert-threshold: "0.7"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-monitoring-ingress
  namespace: identity-monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - identity-monitoring.local
    secretName: identity-tls
  rules:
  - host: identity-monitoring.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: identity-api-service
            port:
              number: 8000
